spring:
  application:
    name: credential-manager
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/mydb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  servlet:
    context-path: /credential-manager
