spring:
  application:
    name: credential-manager
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: credential-manager:session
    timeout: 30m
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/mydb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  servlet:
    context-path: /credential-manager
    session:
      cookie:
        name: CREDENTIAL_SESSION
        http-only: true
        secure: false
